module BxBlockJobDescription
  class JobDescriptionController < ApplicationController

    # created by punit
    # send job description data templete (skills matriks) and Drop down select data like manageers and overall expericences
    def show
      if current_user.user_role == "client"
        @domain = BxBlockDomain::Domain.all
        preferred_overall_experiences = BxBlockPreferredOverallExperiences::PreferredOverallExperiences.all
        preferred_managers = current_user.managers
        preferred_skill_levels = BxBlockPreferredOverallExperiences::PreferredSkillLevel.all
        if @domain.present?
          render json: { job_description: JobDescriptionSerializer.new(@domain).serializable_hash, preferred_data: {
                   overall_experiences: preferred_overall_experiences.as_json(only: [:id, :experiences_year, :level, :grade]),
                   skill_levels: preferred_skill_levels.as_json(only: [:id, :experiences_year, :level]),
                   managers: preferred_managers.as_json(only: [:id, :name, :email]),
                   currency: currency(),
                 } }, status: :ok
        else
          render json: { error: "Not found any job description" }, status: :unprocessable_entity
        end
      else
        render json: { error: "Not for any user" }, status: :unprocessable_entity
      end
    end

    # created by punit
    # give currency code with symboles
    def currency
      return $currencySymbols = {
               "AED" => "د.إ",
               "AFN" => "Af",
               "ALL" => "Lek",
               "AMD" => "դ",
               "ANG" => "ƒ",
               "AOA" => "Kz",
               "ARS" => "$",
               "AUD" => "$",
               "AWG" => "ƒ",
               "AZN" => "₼",
               "BAM" => "KM",
               "BBD" => "$",
               "BDT" => "৳",
               "BGN" => "лв",
               "BHD" => ".د.ب",
               "BIF" => "FBu",
               "BMD" => "$",
               "BND" => "$",
               "BOB" => "$b",
               "BRL" => "R$",
               "BSD" => "$",
               "BTN" => "Nu.",
               "BWP" => "P",
               "BYR" => "p.",
               "BZD" => "BZ$",
               "CAD" => "$",
               "CDF" => "FC",
               "CHF" => "CHF",
               "CLF" => "UF",
               "CLP" => "$",
               "CNY" => "¥",
               "COP" => "$",
               "CRC" => "₡",
               "CUP" => "⃌",
               "CVE" => "$",
               "CZK" => "Kč",
               "DJF" => "Fdj",
               "DKK" => "kr",
               "DOP" => "RD$",
               "DZD" => "دج",
               "EGP" => "E£",
               "ETB" => "Br",
               "EUR" => "€",
               "FJD" => "$",
               "FKP" => "£",
               "GBP" => "£",
               "GEL" => "ლ",
               "GHS" => "¢",
               "GIP" => "£",
               "GMD" => "D",
               "GNF" => "FG",
               "GTQ" => "Q",
               "GYD" => "$",
               "HKD" => "$",
               "HNL" => "L",
               "HRK" => "kn",
               "HTG" => "G",
               "HUF" => "Ft",
               "IDR" => "Rp",
               "ILS" => "₪",
               "INR" => "₹",
               "IQD" => "ع.د",
               "IRR" => "﷼",
               "ISK" => "kr",
               "JEP" => "£",
               "JMD" => "J$",
               "JOD" => "JD",
               "JPY" => "¥",
               "KES" => "KSh",
               "KGS" => "лв",
               "KHR" => "៛",
               "KMF" => "CF",
               "KPW" => "₩",
               "KRW" => "₩",
               "KWD" => "د.ك",
               "KYD" => "$",
               "KZT" => "₸",
               "LAK" => "₭",
               "LBP" => "£",
               "LKR" => "₨",
               "LRD" => "$",
               "LSL" => "L",
               "LTL" => "Lt",
               "LVL" => "Ls",
               "LYD" => "ل.د",
               "MAD" => "د.م.",
               "MDL" => "L",
               "MGA" => "Ar",
               "MKD" => "ден",
               "MMK" => "K",
               "MNT" => "₮",
               "MOP" => "MOP$",
               "MRO" => "UM",
               "MUR" => "₨",
               "MVR" => ".ރ",
               "MWK" => "MK",
               "MXN" => "$",
               "MYR" => "RM",
               "MZN" => "MT",
               "NAD" => "$",
               "NGN" => "₦",
               "NIO" => "C$",
               "NOK" => "kr",
               "NPR" => "₨",
               "NZD" => "$",
               "OMR" => "﷼",
               "PAB" => "B/.",
               "PEN" => "S/.",
               "PGK" => "K",
               "PHP" => "₱",
               "PKR" => "₨",
               "PLN" => "zł",
               "PYG" => "Gs",
               "QAR" => "﷼",
               "RON" => "lei",
               "RSD" => "Дин.",
               "RUB" => "₽",
               "RWF" => "ر.س",
               "SAR" => "﷼",
               "SBD" => "$",
               "SCR" => "₨",
               "SDG" => "£",
               "SEK" => "kr",
               "SGD" => "$",
               "SHP" => "£",
               "SLL" => "Le",
               "SOS" => "S",
               "SRD" => "$",
               "STD" => "Db",
               "SVC" => "$",
               "SYP" => "£",
               "SZL" => "L",
               "THB" => "฿",
               "TJS" => "TJS",
               "TMT" => "m",
               "TND" => "د.ت",
               "TOP" => "T$",
               "TRY" => "₤",
               "TTD" => "$",
               "TWD" => "NT$",
               "TZS" => "TSh",
               "UAH" => "₴",
               "UGX" => "USh",
               "USD" => "$",
               "UYU" => "$U",
               "UZS" => "лв",
               "VEF" => "Bs",
               "VND" => "₫",
               "VUV" => "VT",
               "WST" => "WS$",
               "XAF" => "FCFA",
               "XCD" => "$",
               "XDR" => "SDR",
               "XOF" => "FCFA",
               "XPF" => "F",
               "YER" => "﷼",
               "ZAR" => "R",
               "ZMK" => "ZK",
               "ZWL" => "Z$",
             }
    end
  end
end
