production:
  secret_key_base: ae9483456dbd84826bf80dd4b795d51f


development:
  secret_key_base: static_secret_key

test:
  secret_key_base: static_test_secret_key


#not_indented: key for all env in once
secret_key_base: global_key_for_all_env